
version: '3'
services:
  db:
    image: postgres:10.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  leaderboard_backend:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/leaderboard
    ports:
      - "5000:3000"
    depends_on:
      - db